### PR TITLE
support deflate

### PR DESCRIPTION
**Pull request by YoungerSun**
support the algorithm deflate in wd_comp.c and drv/hisi_comp.c

### CODE REVIEW

**Comment by hzhuang1** [comment]
Do we support the "deflate" algorithm in current test case? If so, how to run test for this algorithm?

**Comment by YoungerSun** [comment]
Sorry, I have added the test code at 'f8228ef'




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haojian Zhuang"<notifications@github.com&gt;; 
发送时间: 2020年12月31日(星期四) 下午5:44
收件人: "Linaro/uadk"<uadk@noreply.github.com&gt;; 
抄送: "òh"<974979717@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Linaro/uadk] support deflate (#148)





 
Do we support the "deflate" algorithm in current test case? If so, how to run test for this algorithm?

**Comment by hzhuang1** [comment]
Please help to enable the tests on both "deflate" and "gzip" algorithms in "test/sanity_test.sh". Then CI could help whether new changes would break the tests.

**Comment by YoungerSun** [comment]
OK, I'll add the test case after&nbsp;New year's Day



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haojian Zhuang"<notifications@github.com&gt;; 
发送时间: 2020年12月31日(星期四) 下午5:55
收件人: "Linaro/uadk"<uadk@noreply.github.com&gt;; 
抄送: "òh"<974979717@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Linaro/uadk] support deflate (#148)





 
Please help to enable the tests on both "deflate" and "gzip" algorithms in "test/sanity_test.sh". Then CI could help whether new changes would break the tests.

**Comment by hzhuang1** [comment]
No problem. I merge it first. Then you add it later.

**Pull request merged**
