### PR TITLE
Upstream

### PR DESCRIPTION
**Pull request by youngersh**
Add the zlibwrapper for wd comp.

### CODE REVIEW

**Comment by gaozhangfei** [comment]
On x86 build has an issue?

libtool: link: gcc -Wall -O0 -Werror -fno-strict-aliasing -I../include -I.. -g -O2 -Wl,-rpath -Wl,/usr/local/lib -o wd_mempool_test wd_mempool_test.o  -lpthread -L../.libs -l:libwd.so.2 -l:libwd_crypto.so.2 /usr/local/lib/libnuma.so
../.libs/libwd_crypto.so.2: undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
Makefile:445: recipe for target 'wd_mempool_test' failed
make[2]: *** [wd_mempool_test] Error 1
make[2]: Leaving directory '/home/zhangfei/work/wrapper/uadk/test'
Makefile:490: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/zhangfei/work/wrapper/uadk/test'
Makefile:880: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

$ cat build.sh 
mkdir -p /tmp/build
./cleanup.sh
./autogen.sh
./configure --prefix=/tmp/build
make -j4
make install

Did I get something wrong?

**Comment by youngersh** [comment]
> 



> On x86 build has an issue?
> 
> libtool: link: gcc -Wall -O0 -Werror -fno-strict-aliasing -I../include -I.. -g -O2 -Wl,-rpath -Wl,/usr/local/lib -o wd_mempool_test wd_mempool_test.o -lpthread -L../.libs -l:libwd.so.2 -l:libwd_crypto.so.2 /usr/local/lib/libnuma.so ../.libs/libwd_crypto.so.2: undefined reference to `pthread_atfork' collect2: error: ld returned 1 exit status Makefile:445: recipe for target 'wd_mempool_test' failed make[2]: *** [wd_mempool_test] Error 1 make[2]: Leaving directory '/home/zhangfei/work/wrapper/uadk/test' Makefile:490: recipe for target 'install-recursive' failed make[1]: *** [install-recursive] Error 1 make[1]: Leaving directory '/home/zhangfei/work/wrapper/uadk/test' Makefile:880: recipe for target 'install-recursive' failed make: *** [install-recursive] Error 1
> 
> $ cat build.sh mkdir -p /tmp/build ./cleanup.sh ./autogen.sh ./configure --prefix=/tmp/build make -j4 make install
> 
> Did I get something wrong?

**Comment by youngersh** [comment]
> On x86 build has an issue?
> 
> libtool: link: gcc -Wall -O0 -Werror -fno-strict-aliasing -I../include -I.. -g -O2 -Wl,-rpath -Wl,/usr/local/lib -o wd_mempool_test wd_mempool_test.o -lpthread -L../.libs -l:libwd.so.2 -l:libwd_crypto.so.2 /usr/local/lib/libnuma.so ../.libs/libwd_crypto.so.2: undefined reference to `pthread_atfork' collect2: error: ld returned 1 exit status Makefile:445: recipe for target 'wd_mempool_test' failed make[2]: *** [wd_mempool_test] Error 1 make[2]: Leaving directory '/home/zhangfei/work/wrapper/uadk/test' Makefile:490: recipe for target 'install-recursive' failed make[1]: *** [install-recursive] Error 1 make[1]: Leaving directory '/home/zhangfei/work/wrapper/uadk/test' Makefile:880: recipe for target 'install-recursive' failed make: *** [install-recursive] Error 1
> 
> $ cat build.sh mkdir -p /tmp/build ./cleanup.sh ./autogen.sh ./configure --prefix=/tmp/build make -j4 make install
> 
> Did I get something wrong?

I built this in x86 too, and didn't meet this problem. The gcc version is 9.4.0.

**Comment by gaozhangfei** [comment]
diff --git a/test/Makefile.am b/test/Makefile.am
index 81e2d2c..a78d6b1 100644
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -1,4 +1,4 @@
-AM_CFLAGS=-Wall -O0 -Werror -fno-strict-aliasing -I$(top_srcdir)/include -I$(top_srcdir) -lpthread
+AM_CFLAGS=-Wall -O0 -Werror -fno-strict-aliasing -I$(top_srcdir)/include -I$(top_srcdir)
 
 bin_PROGRAMS=wd_mempool_test
 wd_mempool_test_SOURCES=wd_mempool_test.c
@@ -8,7 +8,7 @@ AM_CFLAGS+=-Bstatic
 wd_mempool_test_LDADD=../.libs/libwd.a ../.libs/libwd_crypto.a \
                        ../.libs/libhisi_sec.a -lnuma
 else
-wd_mempool_test_LDADD=-L../.libs -l:libwd.so.2 -l:libwd_crypto.so.2 -lnuma
+wd_mempool_test_LDADD=-L../.libs -l:libwd.so.2 -l:libwd_crypto.so.2 -lnuma -lpthread

**Comment by gaozhangfei** [comment]
do we need to add more comments to functions in wd_zlibwrapper.h? 
It is too simple and confusing, like wd_deflateInit & wd_deflateInit2, since there is no sample code.

**Comment by youngersh** [comment]
> do we need to add more comments to functions in wd_zlibwrapper.h? It is too simple and confusing, like wd_deflateInit & wd_deflateInit2, since there is no sample code.

OK, I'll follow the zlib.h to add comments for the interface.

**Comment by Liulongfang** [comment]
The title of the patch is written clearly.

**Comment by gaozhangfei** [comment]
x86 ubuntu 16.04 build fail

**Comment by gaozhangfei** [comment]
+1

**Review by Liulongfang — APPROVED** [review]
OK， +1

**Pull request merged**
