### PR TITLE
wd: sec: remove ctx_num limitation

### PR DESCRIPTION
**Pull request by gaozhangfei**
Nginx doest fork worker processes after master process
So remove the limitaiton here to make fork possible

Signed-off-by: Zhangfei Gao <zhangfei.gao@linaro.org>

### CODE REVIEW

**Comment by hzhuang1** [comment]
@Liulongfang Please help to review this pull request.

**Review by Liulongfang — COMMENTED** [review]
After removing it, how to prevent repeated initialization? Repeated initialization will lead to resource leakage

**Comment by gaozhangfei** [comment]
1. uadk is a library, which should not prevent an application double initializes.
 Instead it is applications' responsibility.
for example, glibc does not prevent application double malloc without free

2. It's incorrect to use a static variable prevent double initialization.
Considering multi-process.
Parent init, static a = true.
fork
child can not init again since static a == true.
Is this expected?

This is why nginx fail to boot, since digest and cipher are used in master process to init.

**Comment by gaozhangfei** [comment]
1. uadk is a library, which should not prevent an application double initializes.
 Instead it is applications' responsibility.
for example, glibc does not prevent application double malloc without free

2. It's incorrect to use a static variable prevent double initialization.
Considering multi-process.
Parent init, static a = true.
fork
child can not init again since static a == true.
Is this expected?

This is why nginx fail to boot, since digest and cipher are used in master process to init.

**Comment by Liulongfang** [comment]
What you said is reasonable, but your modification method did not solve the problem you mentioned, and this modification will lead to resource leakage.

**Comment by gaozhangfei** [comment]
how cause resource leakage?

**Comment by Liulongfang** [comment]
You can look at the wd_cipher_uninit(), all the free resources inside have been leaked.

**Comment by gaozhangfei** [comment]
void wd_cipher_uninit(void)
{
        void *priv = wd_cipher_setting.priv;

        if (!priv)
                return;

        wd_cipher_setting.driver->exit(priv);
        wd_cipher_setting.priv = NULL;
        free(priv);

        wd_uninit_async_request_pool(&wd_cipher_setting.pool);
        wd_clear_sched(&wd_cipher_setting.sched);
        wd_clear_ctx_config(&wd_cipher_setting.config);
}

any relation with wd_cipher_setting.config.ctx_num?

**Pull request closed without merging**
