### PR TITLE
some bugfix and cleancode for uadk

### PR DESCRIPTION
**Pull request by tq444**
Chenghai Huang (13):
  uadk: code cleanup
  uadk: code cleanup for error codes and variable type
  uadk: Add file association
  uadk: fix the failure process bug
  uadk: fix the failure process bug
  uadk: fix the failure process bug
  uadk: bugfix
  uadk v1: adapter code cleanup
  uadk v1: fix wd_rng resource release bug
  uadk v1: code cleanup for error codes and header files
  uadk: concentrate the same definitions
  uadk v1: optimize the function length
  uadk v1: concentrate the same definitions

Longfang Liu (1):
  uadk: fixed some input parameter checking issues

Qi Tao (4):
  uadk/v1: check whether the data address pointer is not null
  uadk: modify improper comments.
  uadk/v1: add null pointer check.
  uadk/v1: fix static compilation error

Wenkai Lin (3):
  uadk/v1: remove print actions after wd_get_cookies
  uadk: fix header file is not self contained
  uadk: fix sec send and recv check failed

Yang Shen (1):
  uadk/v1/comp: add comp ctx parameters check

Zhiqi Song (1):
  uadk/sec: add a return value judgement

### CODE REVIEW

**Comment by gaozhangfei** [comment]
still get build error
/home/linaro/work/configs/uadk/uadk/v1/wd_util.c:188: multiple definition of `wd_check_src_dst'; ../.libs/libwd_comp.a(wd_util.o):/home/linaro/work/configs/uadk/uadk/wd_util.c:464: first defined here

**Comment by gaozhangfei** [comment]
./configure --enable-static --disable-shared --with-static_drv 编译不过

**Comment by tq444** [comment]
> ./configure --enable-static --disable-shared --with-static_drv 编译不过

sh autogen.sh     
 ./configure
make -j32
动态编译没有问题，可以用动态编译来编吗？

**Comment by tq444** [comment]
> ./configure --enable-static --disable-shared --with-static_drv 编译不过
This issue has been resolved

**Comment by gaozhangfei** [comment]
patch/0003-uadk-v1-remove-print-actions-after-wd_get_cookies.patch
------------------------------------------------------------------
ERROR: Unrecognized email address: 'Wenkai Lin <linwenkai6hisilicon.com>'
#9: 
Signed-off-by: Wenkai Lin <linwenkai6hisilicon.com>

ERROR: Missing Signed-off-by: line by nominal patch author ''

total: 2 errors, 0 warnings, 33 lines checked

patch/0001-Revert-uadk-wd_alg-add-registering-driver-parameters.patch
---------------------------------------------------------------------
ERROR: Missing Signed-off-by: line(s)

**Comment by gaozhangfei** [comment]
Other than the signed off, tested OK

**Review by Liulongfang — APPROVED** [review]
looks good to me

**Comment by CaptainMiaow** [comment]
\lgtm

**Review by CaptainMiaow — APPROVED** [review]

**Comment by tq444** [comment]
> ## patch/0003-uadk-v1-remove-print-actions-after-wd_get_cookies.patch
> ERROR: Unrecognized email address: 'Wenkai Lin <linwenkai6hisilicon.com>' #9: Signed-off-by: Wenkai Lin <linwenkai6hisilicon.com>
> 
> ERROR: Missing Signed-off-by: line by nominal patch author ''
> 
> total: 2 errors, 0 warnings, 33 lines checked

This error has been fixed

**Comment by IAMHCHCH** [comment]
\lgtm

**Review by IAMHCHCH — APPROVED** [review]
\lgtm

**Comment by IAMHCHCH** [comment]
\lgtm

**Comment by lin755** [comment]
\lgtm

**Pull request merged**
