### PR TITLE
bugfix for uadk

### PR DESCRIPTION
**Pull request by tq444**
Longfang Liu (2):
  uadk_tools: add segfault locating function
  uadk: bugfix CE driver initialization problem

Wenkai Lin (5):
  uadk/v1: fix for atomic memory order
  uadk: replace wd_lock to pthread_spinlock
  uadk/v1: fix for wd_lock implementation
  uadk: fix for env uninit segment fault
  uadk/v1: replace wd_spinlock to pthread_spin_lock

Yang Shen (1):
  uadk/v1/drv: hisi_zip_udrv - fix the wrong literal buffer size

Zhiqi Song (1):
  uadk/v1/hpre: remove redundant comments

 drv/hash_mb/hash_mb.c                     |  4 ++
 drv/isa_ce_sm3.c                          |  6 +-
 drv/isa_ce_sm4.c                          |  4 ++
 uadk_tool/benchmark/hpre_uadk_benchmark.c |  1 +
 uadk_tool/benchmark/hpre_wd_benchmark.c   |  1 +
 uadk_tool/benchmark/sec_soft_benchmark.c  |  1 +
 uadk_tool/benchmark/sec_uadk_benchmark.c  |  1 +
 uadk_tool/benchmark/sec_wd_benchmark.c    |  1 +
 uadk_tool/benchmark/trng_wd_benchmark.c   |  1 +
 uadk_tool/benchmark/uadk_benchmark.c      | 15 +++++
 uadk_tool/benchmark/uadk_benchmark.h      |  3 +
 uadk_tool/benchmark/zip_uadk_benchmark.c  |  1 +
 uadk_tool/benchmark/zip_wd_benchmark.c    |  1 +
 v1/drv/hisi_hpre_udrv.c                   | 14 +----
 v1/drv/hisi_qm_udrv.c                     | 51 +++++++++++-----
 v1/drv/hisi_qm_udrv.h                     |  4 +-
 v1/drv/hisi_rng_udrv.c                    | 25 +++++---
 v1/drv/hisi_rng_udrv.h                    |  2 +-
 v1/drv/hisi_zip_udrv.c                    | 14 ++---
 v1/wd_util.c                              | 17 ++++--
 wd_mempool.c                              | 74 +++++++++++------------
 wd_util.c                                 |  1 +
 22 files changed, 154 insertions(+), 88 deletions(-)

### CODE REVIEW

**Comment by lin755** [comment]
lgtm

**Comment by youngersh** [comment]
lgtm

**Comment by gaozhangfei** [comment]
+1

One small question:
since all other patches uses pthread_spinlock, how about patch "[uadk/v1: fix for wd_lock implementation]" change to pthread_spinlock as well?

**Comment by lin755** [comment]
> +1
> 
> One small question: since all other patches uses pthread_spinlock, how about patch "[uadk/v1: fix for wd_lock implementation]" change to pthread_spinlock as well?

wd_lock is better to be retained for compatibility, because it is already used in the external structure q_info in wd_util.h.

**Comment by gaozhangfei** [comment]
> > +1
> > One small question: since all other patches uses pthread_spinlock, how about patch "[uadk/v1: fix for wd_lock implementation]" change to pthread_spinlock as well?
> 
> wd_lock is better to be retained for compatibility, because it is already used in the external structure q_info in wd_util.h.

OK, thanks for reply

**Pull request merged**
