### PR TITLE
support ecdsa for hpre and bugfix for zip parese sqe

### PR DESCRIPTION
**Pull request by lin755**

### CODE REVIEW

**Comment by hzhuang1** [comment]
New interfaces are added. Do they verified on the platform?

**Comment by lin755** [comment]
> New interfaces are added. Do they verified on the platform?

platform not support sva ecdsa yet, will verify in the later version.

**Comment by hzhuang1** [comment]
Please rebase the patch on dev branch. We hope all patches on master branch could be verified.

**Comment by lin755** [comment]
the patch has been sent to dev branch, close this pr.

**Comment by wangzhou** [comment]
I think the second patch about zip should be move to master branch

**Pull request closed without merging**
