### PR TITLE
uadk/ecc: some bugfix about data processing

### PR DESCRIPTION
**Pull request by CaptainMiaow**
1. uadk/v1/ecc: bugfix buffer overwritten of sm2 decryption
2. uadk/ecc: cleanup sm2 dec out code
3. uadk/v1/ecc: bugfix incorrect parameter length
4. uadk/ecc: bugfix incorrect parameter length

### CODE REVIEW

**Comment by gaozhangfei** [comment]
+1

**Review by Liulongfang — APPROVED** [review]
OK， +1

**Comment by gaozhangfei** [comment]
one check warning

WARNING: Statements should start on a tabstop
#40: FILE: v1/drv/hisi_hpre_udrv.c:1118:
+	 if (!e || !e->data) {

total: 0 errors, 1 warnings, 109 lines checked

**Comment by gaozhangfei** [comment]
thanks, +1

**Pull request merged**
