### PR TITLE
 uadk/v1: check whether the data address pointer is not null.

### PR DESCRIPTION
**Pull request by tq444**
Qi Tao (1):
  uadk/v1: check whether the data address pointer is not null.

Yang Shen (1):
  uadk/v1/comp - add comp ctx parameters check

### CODE REVIEW

**Comment by youngersh** [comment]
sec/uadk: resolve white-box security review comments. -- Please rewrite the commit.

**Comment by tq444** [comment]
> sec/uadk: resolve white-box security review comments. -- Please rewrite the commit.

I've modified

**Comment by gaozhangfei** [comment]
/usr/bin/ld: ../.libs/libwd_comp.a(lt4-wd_util.o): in function `wd_check_src_dst':
/home/linaro/work/configs/uadk/uadk/v1/wd_util.c:188: multiple definition of `wd_check_src_dst'; ../.libs/libwd_comp.a(wd_util.o):/home/linaro/work/configs/uadk/uadk/wd_util.c:464: first defined here     
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:505: uadk_tool] Error 1

**Comment by gaozhangfei** [comment]
编译脚本报错
/usr/bin/ld: ../.libs/libwd_comp.a(lt4-wd_util.o): in function `wd_check_src_dst':
/home/linaro/work/configs/uadk/uadk/v1/wd_util.c:188: multiple definition of `wd_check_src_dst'; ../.libs/libwd_comp.a(wd_util.o):/home/linaro/work/configs/uadk/uadk/wd_util.c:464: first defined here     
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:505: uadk_tool] Error 1
make[2]: Leaving directory '/home/linaro/work/configs/uadk/uadk/uadk_tool'
make[1]: *** [Makefile:963: all-recursive] Error 1
make[1]: Leaving directory '/home/linaro/work/configs/uadk/uadk'
make: *** [Makefile:590: all] Error 2
单独遍没有，可能是没编译v1

**Comment by tq444** [comment]
> 编译脚本报错 /usr/bin/ld: ../.libs/libwd_comp.a(lt4-wd_util.o): in function `wd_check_src_dst': /home/linaro/work/configs/uadk/uadk/v1/wd_util.c:188: multiple definition of `wd_check_src_dst'; ../.libs/libwd_comp.a(wd_util.o):/home/linaro/work/configs/uadk/uadk/wd_util.c:464: first defined here collect2: error: ld returned 1 exit status make[2]: *** [Makefile:505: uadk_tool] Error 1 make[2]: Leaving directory '/home/linaro/work/configs/uadk/uadk/uadk_tool' make[1]: *** [Makefile:963: all-recursive] Error 1 make[1]: Leaving directory '/home/linaro/work/configs/uadk/uadk' make: *** [Makefile:590: all] Error 2 单独遍没有，可能是没编译v1

这个是怎么编出来的，我本地编译没有出现这个问题

**Comment by gaozhangfei** [comment]
> > 编译脚本报错 /usr/bin/ld: ../.libs/libwd_comp.a(lt4-wd_util.o): in function `wd_check_src_dst': /home/linaro/work/configs/uadk/uadk/v1/wd_util.c:188: multiple definition of `wd_check_src_dst'; ../.libs/libwd_comp.a(wd_util.o):/home/linaro/work/configs/uadk/uadk/wd_util.c:464: first defined here collect2: error: ld returned 1 exit status make[2]: *** [Makefile:505: uadk_tool] Error 1 make[2]: Leaving directory '/home/linaro/work/configs/uadk/uadk/uadk_tool' make[1]: *** [Makefile:963: all-recursive] Error 1 make[1]: Leaving directory '/home/linaro/work/configs/uadk/uadk' make: *** [Makefile:590: all] Error 2 单独遍没有，可能是没编译v1
> 
> 这个是怎么编出来的，我本地编译没有出现这个问题

我也不确定可是误报， 没细看，用configs编的
本地测试
git clone https://git.linaro.org/ci/job/configs
cd configs/uadk
./builders.sh

cd uadk
git checkout master
git checkout -b 587
git pull origin pull/587/head
cd ..
./builders.sh

1.host 安装openssl1.1 (3.0 环境uadk编译有点问题)
2.ImportError: No module named numpy
sudo apt-get install python-numpy

**Pull request closed without merging**
