### PR TITLE
Add dynamic driver loading function

### PR DESCRIPTION
**Pull request by Liulongfang**
Update the current driver adaptation and usage method, from fixed
use of Hisilicon device driver to automatic registration of the
driver according to the algorithm.

When the algorithm API layer uses the driver, it is no longer
bound to the fixed device driver, but dynamically obtained
and stored according to the algorithm query to use.

Update the driver and API layer of the zip module, keep the
function of the init interface unchanged, update the implementation
of the init2 interface and match the dynamic loading function.

### CODE REVIEW

**Comment by hzhuang1** [comment]
+1

**Comment by gaozhangfei** [comment]
the doc design.md load pic seems not correct.

How to use fallback, and what's the policy?
Is it transparent to the user's app (called by the drive itself) or controlled by the user?

**Comment by Liulongfang** [comment]
> 
I tried to open this document and it can be opened normally. 

The fallback function can be enabled by configuring the task_type parameter of the init2 interface as TASK_MIX. Through this parameter, you can configure whether the current business is hardware computing, software instruction computing or hybrid computing

**Comment by gaozhangfei** [comment]
> > 
> 
> I tried to open this document and it can be opened normally.

OK, it may my issue, I checked from your git tree.

> 
> The fallback function can be enabled by configuring the task_type parameter of the init2 interface as TASK_MIX. Through this parameter, you can configure whether the current business is hardware computing, software instruction computing or hybrid computing

Yes, driver then get two func pointers
Then how to switch them, according to packet size or cpu usage?
 is it decided from user or some policy?

**Comment by Liulongfang** [comment]
> > > 
> > 
> > 
> > I tried to open this document and it can be opened normally.
> 
> OK, it may my issue, I checked from your git tree.
> 
> > The fallback function can be enabled by configuring the task_type parameter of the init2 interface as TASK_MIX. Through this parameter, you can configure whether the current business is hardware computing, software instruction computing or hybrid computing
> 
> Yes, driver then get two func pointers Then how to switch them, according to packet size or cpu usage? is it decided from user or some policy?

The fallback driver will be transparently transmitted directly to the device driver. If the current device has some algorithm or hardware limitations, which makes it impossible to handle some scenarios (such as short packets, unsupported algorithm specifications, etc.), you can forward the task to the fallback driver through the fallback driver. Therefore, how to switch the driver and when to switch the driver are all determined by the control of the device driver itself, and there is no longer an algorithm API layer for unified processing, thereby enhancing the compatibility of the device

**Comment by gaozhangfei** [comment]
> > > > 
> > > 
> > > 
> > > I tried to open this document and it can be opened normally.
> > 
> > 
> > OK, it may my issue, I checked from your git tree.
> > > The fallback function can be enabled by configuring the task_type parameter of the init2 interface as TASK_MIX. Through this parameter, you can configure whether the current business is hardware computing, software instruction computing or hybrid computing
> > 
> > 
> > Yes, driver then get two func pointers Then how to switch them, according to packet size or cpu usage? is it decided from user or some policy?
> 
> The fallback driver will be transparently transmitted directly to the device driver. If the current device has some algorithm or hardware limitations, which makes it impossible to handle some scenarios (such as short packets, unsupported algorithm specifications, etc.), you can forward the task to the fallback driver through the fallback driver. Therefore, how to switch the driver and when to switch the driver are all determined by the control of the device driver itself, and there is no longer an algorithm API layer for unified processing, thereby enhancing the compatibility of the device

OK, so this is out of the user's control and decided by the driver itself.

Now the driver gets two ops, one hardware, and the other software (for example). 

Some scenarios, 
Big packets use hardware, and small packets choose software and need a threshold, which may differ according to algorithms.
Or some other scenarios like bandwidth.
Can we add it later in this framework?

**Comment by Liulongfang** [comment]
>

**Comment by Liulongfang** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I tried to open this document and it can be opened normally.
> > > 
> > > 
> > > OK, it may my issue, I checked from your git tree.
> > > > The fallback function can be enabled by configuring the task_type parameter of the init2 interface as TASK_MIX. Through this parameter, you can configure whether the current business is hardware computing, software instruction computing or hybrid computing
> > > 
> > > 
> > > Yes, driver then get two func pointers Then how to switch them, according to packet size or cpu usage? is it decided from user or some policy?
> > 
> > 
> > The fallback driver will be transparently transmitted directly to the device driver. If the current device has some algorithm or hardware limitations, which makes it impossible to handle some scenarios (such as short packets, unsupported algorithm specifications, etc.), you can forward the task to the fallback driver through the fallback driver. Therefore, how to switch the driver and when to switch the driver are all determined by the control of the device driver itself, and there is no longer an algorithm API layer for unified processing, thereby enhancing the compatibility of the device
> 
> OK, so this is out of the user's control and decided by the driver itself.
> 
> Now the driver gets two ops, one hardware, and the other software (for example).
> 
> Some scenarios, Big packets use hardware, and small packets choose software and need a threshold, which may differ according to algorithms. Or some other scenarios like bandwidth. Can we add it later in this framework?

Yes, after the integration of this framework, there are these requirements. The HiSilicon device driver that has been enabled in UADK can add these functions, and can be identified and processed according to different algorithms

**Pull request merged**
