### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by youngersh**
1、fix some wd_zlibwrapper bugs
2、fix wd_util

### CODE REVIEW

**Comment by gaozhangfei** [comment]
tmp/0007-uadk-wd-fix-error-shmid-for-multiprocess.patch
-------------------------------------------------------
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#6: 
'shmid' is identifier for share memory. And it will be updated after process

ERROR: open brace '{' following function definitions go on the next line
#111: FILE: wd_util.c:185:
+static void wd_shm_delete(struct wd_ctx_config_internal *in)
+ {

WARNING: please, no spaces at the start of a line
#112: FILE: wd_util.c:186:
+ {$

total: 1 errors, 2 warnings, 145 lines checked

**Comment by youngersh** [comment]
> 
Fixed. 
Thx.

**Comment by gaozhangfei** [comment]
Just curios, in what case requires shm?

**Comment by youngersh** [comment]
> Just curios, in what case requires shm?

UADK support  a shared memory to get request count with uadk_tool dfx. So if users set the log level in rsyslog.conf, the shared memory will be created.

**Comment by Liulongfang** [comment]
> Just curios, in what case requires shm?

Obtain uadk status data through this shm during task operation

**Review by Liulongfang — COMMENTED** [review]
looks good to me

**Pull request merged**
