### PR TITLE
uadk: simplify msg_pool via removing ctx_id

### PR DESCRIPTION
**Pull request by gaozhangfei**
The msg_pool does not need two dimensions, one dimension is enough, get the first empty msg from the list and use the index as tag. So the hardware info ctx_id can be removed.

### CODE REVIEW

**Comment by gaozhangfei** [comment]
for one algorithm, is WD_POOL_MAX_ENTRIES(1024 ) enough?
and user can set
/* If user set valid msg num, use user's. */
        get_ctx_msg_num(config->cap, &msg_num);

Now we alloc  async_ctx_num * WD_POOL_MAX_ENTRIES
async_ctx_num is async * nodes * op, is this a waste?

**Comment by Liulongfang** [comment]
> for one algorithm, is WD_POOL_MAX_ENTRIES(1024 ) msgs enough? and user can set msg num /* If user set valid msg num, use user's. */ get_ctx_msg_num(config->cap, &msg_num);
> 
> Now we alloc async_ctx_num * WD_POOL_MAX_ENTRIES async_ctx_num is async * nodes * op, is this a waste?

Now after modification, as a whole, performance bottlenecks may occur in multi-threaded scenarios. You can use uadk_tool benchmark to test the modified performance to ensure that performance is not affected.

**Comment by gaozhangfei** [comment]
> > for one algorithm, is WD_POOL_MAX_ENTRIES(1024 ) msgs enough? and user can set msg num /* If user set valid msg num, use user's. */ get_ctx_msg_num(config->cap, &msg_num);
> > Now we alloc async_ctx_num * WD_POOL_MAX_ENTRIES async_ctx_num is async * nodes * op, is this a waste?
> 
> Now after modification, as a whole, performance bottlenecks may occur in multi-threaded scenarios. You can use uadk_tool benchmark to test the modified performance to ensure that performance is not affected.

Yes, I am also concern the perf for multi-thread, but looks not see difference from the test
Maybe the incorrect test script?

with this patch
aes-128-ecb     8192Bytes       7893362.0KB/s   986.7Kops       799.55%
aes-128-ecb     8192Bytes       7895578.0KB/s   986.9Kops       799.60%
aes-128-ecb     8192Bytes       7895217.6KB/s   986.9Kops       799.60%
aes-128-ecb     8192Bytes       7899500.8KB/s   987.4Kops       799.65%
aes-128-ecb     8192Bytes       7898315.6KB/s   987.3Kops       799.50%
aes-128-ecb     8192Bytes       7904385.2KB/s   988.0Kops       799.60%

original
aes-128-ecb     8192Bytes       7897656.4KB/s   987.2Kops       799.55%
aes-128-ecb     8192Bytes       7896188.0KB/s   987.0Kops       799.55%
aes-128-ecb     8192Bytes       7896778.8KB/s   987.1Kops       799.60%


Test
for x in {1..3}
do
        echo $x
        numactl --cpubind=0 --membind=0 \
        ./uadk_tool benchmark --alg aes-128-ecb --mode sva --opt 0 --sync --pktlen 8192 --seconds 20 --multi 1 --thread 8 --ctxnum 8
done

The reason is we use ctx (hardware) info to get message in algorithm layer, which is a bit strange.
The msg should not related with hardware, only software related, ie, algo get one msg in send, and get such msg with idx in asyn recv, it does not matter which ctx.


For example, we may move the ctx, pool, shced out of the algorithm layer.

**Comment by Liulongfang** [comment]
> > > for one algorithm, is WD_POOL_MAX_ENTRIES(1024 ) msgs enough? and user can set msg num /* If user set valid msg num, use user's. */ get_ctx_msg_num(config->cap, &msg_num);
> > > Now we alloc async_ctx_num * WD_POOL_MAX_ENTRIES async_ctx_num is async * nodes * op, is this a waste?
> > 
> > 
> > Now after modification, as a whole, performance bottlenecks may occur in multi-threaded scenarios. You can use uadk_tool benchmark to test the modified performance to ensure that performance is not affected.
> 
> Yes, I am also concern the perf for multi-thread, but looks not see difference from the test Maybe the incorrect test script?
> 
> with this patch aes-128-ecb 8192Bytes 9089525.2KB/s 1136.2Kops 1483.80% aes-128-ecb 8192Bytes 9107025.6KB/s 1138.4Kops 1487.70% aes-128-ecb 8192Bytes 9093035.2KB/s 1136.6Kops 1490.65%
> 
> original aes-128-ecb 8192Bytes 9079088.4KB/s 1134.9Kops 1481.55% aes-128-ecb 8192Bytes 9115990.0KB/s 1139.5Kops 1486.25% aes-128-ecb 8192Bytes 9087795.6KB/s 1136.0Kops 1482.60%
> 
> Test for x in {1..3} do echo $x numactl --cpubind=0 --membind=0 ./uadk_tool benchmark --alg aes-128-ecb --mode sva --opt 0 --async --pktlen 8192 --seconds 20 --multi 1 --thread 8 --ctxnum 8 done
> 
> The reason is we use ctx (hardware) info to get message in algorithm layer, which is a bit strange. The msg should not related with hardware, only software related, ie, algo get one msg in send, and get such msg with idx in asyn recv, it does not matter which ctx.
> 
> For example, we may move the ctx, pool, shced out of the algorithm layer.

Your test mode above is an 8KB long packet in asynchronous mode. This kind of long packet is not sensitive to the time it takes to obtain the resource pool. In this case, you need to test the 1024Byte short message. And test 16, 24, 32, 48, 64 threads and multiple queues concurrently.
Another question, all your queues share a msg_pool. Then as the number of queues increases, the number of msg each thread can obtain will decrease. The competition between them will intensify, and the while operation in wd_get_msg_from_pool() will cause query failure.
However, you haven't encountered any of them here. Therefore, this test still cannot explain the problem.

**Comment by gaozhangfei** [comment]
有具体测试命令么，给个命令我测下看下对性能影响多大。
init2 现在只能用env? 参数指定多ctx没用。

我看其他msg pool也没这么按多线程设计的。就是给个size, num就完了。get_msg可能不是瓶颈。

主要是考虑到软件硬件共用一个pool, 
现在的方法绑定ctx, 除非软件也申请ctx, 且id 不同，不然有冲突。那就得统一申请ctx。
而且全耦合在一起了。算法层得知道硬件ctx 信息。
当然其实相同ctx id也没事，一个pool也行，

现在指令集也就申请2个ctx， 一个同步，一个异步。其实多线程也只用到了一维的pool, 对应那个异步ctx。

我也在考虑可有什么更好的办法，比如一个sess一个pool，
但poll 这里是统一根据tag来找msg，除非改动poll, 传递sess信息。

**Comment by gaozhangfei** [comment]
这套设计软算都用不上啊，软算多线程用的都是一个ctx_id的pool
不可能为了用多维的pool, 故意申请多个ctx, 且每个ctx id都不一样吧

即便是硬件，ctx 跟多线程也没必然联系吧，比如2个ctx, 8个线程啥的。

ctx是硬件，消息队列纯软件，这两个强耦合，真的好么。

**Comment by Liulongfang** [comment]
> 有具体测试命令么，给个命令我测下看下对性能影响多大。 init2 现在只能用env? 参数指定多ctx没用。
> 
> 我看其他msg pool也没这么按多线程设计的。就是给个size, num就完了。get_msg可能不是瓶颈。
> 
> 主要是考虑到软件硬件共用一个pool, 现在的方法绑定ctx, 除非软件也申请ctx, 且id 不同，不然有冲突。那就得统一申请ctx。 而且全耦合在一起了。算法层得知道硬件ctx 信息。 当然其实相同ctx id也没事，一个pool也行，
> 
> 现在指令集也就申请2个ctx， 一个同步，一个异步。其实多线程也只用到了一维的pool, 对应那个异步ctx。
> 
> 我也在考虑可有什么更好的办法，比如一个sess一个pool， 但poll 这里是统一根据tag来找msg，除非改动poll, 传递sess信息。

uadk_tool benchmark --alg aes-128-ecb --mode sva --opt 0 --async --pktlen 1024 --seconds 5 --thread 32 --multi 1 --ctxnum 32

**Comment by Liulongfang** [comment]
> 这套设计软算都用不上啊，软算多线程用的都是一个ctx_id的pool 不可能为了用多维的pool, 故意申请多个ctx, 且每个ctx id都不一样吧
> 
> 即便是硬件，ctx 跟多线程也没必然联系吧，比如2个ctx, 8个线程啥的。
> 
> ctx是硬件，消息队列纯软件，这两个强耦合，真的好么。

软算现在是用不上的，但是需要保证硬算功能和性能正常。

**Comment by gaozhangfei** [comment]
测下来确实有性能损耗，
上次可能没测对，因为是库，需要重编

**Pull request closed without merging**
