### PR TITLE
uadk: fix code compatibility issue

### PR DESCRIPTION
**Pull request by tq444**
Qi Tao (2):
    uadk: fix for hashagg include files
    uadk: fix code compatibility issue
 
   drv/hisi_sec.c           | 4 ++--
   include/drv/wd_agg_drv.h | 1 +
   include/wd_agg.h         | 1 -
   include/wd_dae.h         | 1 +
   wd_cipher.c              | 6 ------
   5 files changed, 4 insertions(+), 9 deletions(-)

### CODE REVIEW

**Comment by lin755** [comment]
lgtm
@gaozhangfei

**Comment by gaozhangfei** [comment]
这是解决https://github.com/Linaro/uadk/pull/640问题的么？ 我测试还不行
openssl speed -engine uadk_engine -async_jobs 1 -evp aes-128-cbc
switch to soft cipher.

openssl speed -engine uadk_engine -evp aes-128-cbc
switch to soft cipher.

**Comment by gaozhangfei** [comment]
+1, Thanks

**Review by Liulongfang — APPROVED** [review]
looks good to me

**Pull request merged**
