### PR TITLE
Add schdule cache feature.

### PR DESCRIPTION
**Pull request by mizhenkun**
Add schedule cache

### CODE REVIEW

**Review by hzhuang1 — COMMENTED** [review]
It's better to split it into two small patches. One is to fix in test_hisi_sec.c, and the other is for schedule cache.

If you can add more comments in commit for schedule cache, it would be better. It could help other developers/users to understand how it works.

**Comment by mizhenkun** [comment]
> It's better to split it into two small patches. One is to fix in test_hisi_sec.c, and the other is for schedule cache.
> 
> If you can add more comments in commit for schedule cache, it would be better. It could help other developers/users to understand how it works.

I delete the change of test_hisi_sec.c, and add some commit info.

**Comment by wangzhou** [comment]
better to write subject line:

test: sched: xxx

**Comment by mizhenkun** [comment]
> better to write subject line:
> 
> test: sched: xxx

Fixed

**Pull request merged**
