### PR TITLE
doc: update release tag policy

### PR DESCRIPTION
**Pull request by hzhuang1**
Update the policy on release tag.

Each version followes the format of {x}.{y}.{z}. Make use of {y} to indiate the release. The release date must be mentioned in tag comments.

Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>

### CODE REVIEW

**Comment by hzhuang1** [comment]
It's the proposal on release tag policy. Any comment is welcome!

**Comment by Liulongfang** [comment]
Is the version number related to the branch?

**Comment by hzhuang1** [comment]
Excuse me that I didn’t get your point.

The version number in master branch (development branch) should always be libNAME.so.{x}.{y}.{z}. Only {z} is always accumulated.

For the release tag, it should be libNAME.so.{x}.{y}.0. For each release, {y} should be updated either to {y+1} or 0.

If there’s any fix on the release, it should be libNAME.so.{x}.{y}.0-[a-z].

On 14 Oct 2022, at 14:19, Liulongfang ***@***.******@***.***>> wrote:



Is the version number related to the branch?

**Comment by Liulongfang** [comment]
Because the previous discussion said that it may be necessary to create a new release branch version, then this version number will be different on different branches. In other words, how to update the respective version numbers on different branches?

**Comment by hzhuang1** [comment]
At first, I agreed to create a new release branch. But I concerned it may cause too much branches. So I send out my opinions on release tags.

And the most important thing is hard to create link between new date version and development version number. So I suggested to keep using development version number, but changed the meaning of {y} in version number. We could just keep the release date in tag comment.

Both of these are just my personal opinion. If it can’t resolve the problem, it could be discarded. It’s open for discussion.

On 14 Oct 2022, at 17:08, Liulongfang ***@***.******@***.***>> wrote:



Because the previous discussion said that it may be necessary to create a new release branch version, then this version number will be different on different branches. In other words, how to update the respective version numbers on different branches?

**Pull request closed without merging**
