### PR TITLE
uadk: add new algs and bugfix 

### PR DESCRIPTION
**Pull request by tq444**
Qi Tao (2):
  uadk: add compilation options
  uadk_tool: fix error in saving the aead dst data

Wenkai Lin (7):
  uadk: fix for set hashagg session state
  uadk/v1: support the hmac(sm3)-cbc(sm4) algorithm
  uadk: fix for the algorithm name of the aead cbc mode
  uadk/v1: Add stream mode for AES-GCM and SM4-GCM
  uadk/v1: add assoc bytes check
  uadk/v1: set aead msg state for the hardware v2
  uadk/v1: fix input length check for aead stream mode.

Yang Shen (1):
  uadk/v1 - add fair lock to replace CAS

Zhiqi Song (3):
  uadk/hpre: modify privkey transform method of ecc
  v1/hpre: modify privkey transform method of ecc
  uadk/v1: cleanup key format transform function

 Makefile.am                              |  17 +-
 drv/hash_mb/hash_mb.c                    |   4 +
 drv/hisi_comp.c                          |   6 +-
 drv/hisi_dae.c                           |  34 ++-
 drv/hisi_hpre.c                          |  18 +-
 drv/hisi_sec.c                           |   8 +-
 include/crypto/sm4.h                     |  18 ++
 include/wd_rsa.h                         |   2 -
 include/wd_util.h                        |  10 +-
 lib/crypto/sm4.c                         | 176 ++++++++++++++
 uadk_tool/benchmark/sec_uadk_benchmark.c |   6 +
 uadk_tool/benchmark/uadk_benchmark.c     |   6 +-
 uadk_tool/test/test_sec.c                |   4 +-
 v1/drv/hisi_hpre_udrv.c                  |  28 +--
 v1/drv/hisi_qm_udrv.c                    |  51 ++--
 v1/drv/hisi_qm_udrv.h                    |   4 +-
 v1/drv/hisi_sec_udrv.c                   | 296 ++++++++++++++++++++++-
 v1/drv/hisi_sec_udrv.h                   |   9 +-
 v1/drv/hisi_zip_udrv.c                   |  26 +-
 v1/test/hisi_sec_test/test_hisi_sec.c    |   4 +-
 v1/wd_adapter.c                          |   4 +-
 v1/wd_adapter.h                          |   2 +-
 v1/wd_aead.c                             |  67 ++++-
 v1/wd_aead.h                             |  12 +
 v1/wd_cipher.c                           |   2 +-
 v1/wd_digest.c                           |   6 +-
 v1/wd_ecc.c                              |  10 +-
 v1/wd_util.c                             |  31 +++
 v1/wd_util.h                             |   8 +
 wd.c                                     |   2 +-
 wd_aead.c                                |  10 +-
 wd_agg.c                                 |  43 ++--
 wd_alg.c                                 |   2 +
 wd_cipher.c                              |   6 +-
 wd_comp.c                                |  16 +-
 wd_digest.c                              |  14 +-
 wd_ecc.c                                 |  13 -
 wd_mempool.c                             |   2 +-
 wd_rsa.c                                 |   6 +-
 wd_util.c                                |  16 +-
 40 files changed, 792 insertions(+), 207 deletions(-)
 create mode 100644 include/crypto/sm4.h
 create mode 100644 lib/crypto/sm4.c

### CODE REVIEW

**Comment by CaptainMiaow** [comment]
lgtm

**Comment by gaozhangfei** [comment]
ERROR: code indent should use tabs where possible
#223: FILE: lib/crypto/sm4.c:140:
+        __u32 i, j, k, in_len;$

WARNING: please, no spaces at the start of a line
#223: FILE: lib/crypto/sm4.c:140:
+        __u32 i, j, k, in_len;$

total: 1 errors, 2 warnings, 698 lines checked
这两个需要改下

WARNING: Use of volatile is usually wrong: see Documentation/process/volatile-considered-harmful.rst
#226: FILE: v1/wd_util.h:116:
+       volatile __u32 serving;
WARNING: Use of volatile is usually wrong: see Documentation/process/volatile-considered-harmful.rst
#225: FILE: v1/wd_util.h:115:
+       volatile __u32 ticket;
这个不确定

**Comment by tq444** [comment]
> ERROR: code indent should use tabs where possible #223: FILE: lib/crypto/sm4.c:140:
> 
> * ```
>      __u32 i, j, k, in_len;$
>   ```
> 
> WARNING: please, no spaces at the start of a line #223: FILE: lib/crypto/sm4.c:140:
> 
> * ```
>      __u32 i, j, k, in_len;$
>   ```
> 
> total: 1 errors, 2 warnings, 698 lines checked 这两个需要改下
> 
> WARNING: Use of volatile is usually wrong: see Documentation/process/volatile-considered-harmful.rst #226: FILE: v1/wd_util.h:116:
> 
> * ```
>     volatile __u32 serving;
>   ```
> 
> WARNING: Use of volatile is usually wrong: see Documentation/process/volatile-considered-harmful.rst #225: FILE: v1/wd_util.h:115:
> 
> * ```
>     volatile __u32 ticket;
>   ```
> 
> 这个不确定

已解决

**Comment by lin755** [comment]
lgtm

**Comment by Liulongfang** [comment]
It is recommended to send PR for these two feature patches separately for uploading.

**Pull request closed without merging**
