### PR TITLE
cleancode and bugfix for uadk

### PR DESCRIPTION
**Pull request by tq444**
[PATCH 13] 

Chenghai Huang (1):
  uadk - reduce the print rating of specific logs

Hao Fang (1):
  uadk/test: move main function to testsuit.c and rm test_sva_perf.c

Longfang Liu (1):
  uadk: fix some code bugs

Qi Tao (1):
  uadk: add null pointer check

Weili Qian (4):
  Revert "uadk/v1: replace wd_spinlock to pthread_spin_lock"
  Revert "uadk/v1: check queue status before sending doorbells"
  uadk/v1: not check hardware status when BD not processed
  uadk/v1: check queue status before sending doorbells

Wenkai Lin (4):
  uadk: fix for sec software compute check
  uadk: fix for cipher update iv
  uadk/v1: fix for cipher update iv
  uadk/v1: replace wd_spinlock to pthread_spin_lock

Yang Shen (1):
  uadk/cipher - add length check of CBC_CTS mode

 drv/hash_mb/hash_mb.c              |   6 +-
 drv/hisi_comp.c                    |  21 +-
 drv/hisi_dae.c                     |   6 +-
 drv/hisi_hpre.c                    |   8 +-
 drv/hisi_sec.c                     |  61 ++--
 drv/isa_ce_sm3.c                   |   6 +-
 drv/isa_ce_sm4.c                   |   6 +-
 test/hisi_zip_test/Makefile.am     |   2 +-
 test/hisi_zip_test/test_sva_perf.c | 524 -----------------------------
 test/hisi_zip_test/testsuit.c      | 474 +++++++++++++++++++++++++-
 v1/drv/hisi_sec_udrv.c             |  80 ++++-
 v1/drv/hisi_zip_udrv.c             |  40 ++-
 wd_cipher.c                        |  36 +-
 wd_ecc.c                           |   6 +-
 wd_util.c                          |  11 +-
 15 files changed, 684 insertions(+), 603 deletions(-)
 delete mode 100644 test/hisi_zip_test/test_sva_perf.c

### CODE REVIEW

**Comment by haofang111** [comment]
LGTM

**Review by Liulongfang — COMMENTED** [review]
Looks good！

**Comment by qwl731** [comment]
LGTM

**Comment by IAMHCHCH** [comment]
LGTM

**Review by Liulongfang — APPROVED** [review]
LGTM

**Pull request merged**
