### PR TITLE
Sync code clean for wd and qm

### PR DESCRIPTION
**Pull request by lin755**
Signed-off-by: wenkai lin <linwenkai755@qq.com>

### CODE REVIEW

**Comment by hzhuang1** [comment]
Don't use dash in the title. Please help to use colon instead.

Don't leave the comment area as blank.

**Comment by lin755** [comment]
this patch for:
1.make fall through effective
2.some clean for size_t
3.tmp use directly in next ,add intercept

**Comment by hzhuang1** [comment]
For the title, we always write it as the format "{category}: {operation}". For example, "wd: clean for size_t". If it's related to rsa algorithm, we could write "wd: rsa: clean for size_t" or "wd/rsa: clean for size_t".

It's good that you fill the comment in the pull request. But I really hope you could move it to the comment area in the commit. It would help others to check comments in git tree. If the comments are only in the pull request, others couldn't find it from the git tree.

To your patch, it's better to split it since it covers both wd common layer and hisi vendor driver. If a change is related to any interface, we have to make the changes on both wd layer and vendor driver into one commit. Otherwise, we'll suffer build error. If a change is NOT related to any interface, we could split the patch. The rule is to only change a small part at a time. It would be easier to review in the community.

Thanks.

**Comment by lin755** [comment]
> For the title, we always write it as the format "{category}: {operation}". For example, "wd: clean for size_t". If it's related to rsa algorithm, we could write "wd: rsa: clean for size_t" or "wd/rsa: clean for size_t".
> 
> It's good that you fill the comment in the pull request. But I really hope you could move it to the comment area in the commit. It would help others to check comments in git tree. If the comments are only in the pull request, others couldn't find it from the git tree.
> 
> To your patch, it's better to split it since it covers both wd common layer and hisi vendor driver. If a change is related to any interface, we have to make the changes on both wd layer and vendor driver into one commit. Otherwise, we'll suffer build error. If a change is NOT related to any interface, we could split the patch. The rule is to only change a small part at a time. It would be easier to review in the community.
> 
> Thanks.

Thanks for all your advices, I will send another pr and close this later.

**Comment by hzhuang1** [comment]
Close since the patches are migrated into another pull request #205.

**Pull request closed without merging**
